### ISSUE TITLE
Hi, thanks for your code. Are you authors of this article. And I want to ask that how long does it take for a layer of VGG16.

### ISSUE THREAD

**Issue by streamer-AP** [saadmanrafat/Pruning-CNN-Filters-with-RL#1]

**Comment by saadmanrafat** [comment]
Hi there,
No, I'm not the author of the paper. I mentioned this in the descriptions. [Here's the original paper](https://arxiv.org/pdf/1801.07365.pdf). Comparisons and benchmarks have largely been ignored in this repository, unfortunately. So I can't say how long it takes to prune a layer of VGG16. Sorry I couldn't be of help. 

Good Luck with whatever you are working on!
